# this docker compose should be run to aid with the build environment
# by caching apt-lists and debian packages on the host

version: '3'

services:
  apt-cacher-ng:
    build:
      dockerfile: ./apt-cacher.Dockerfile
      context: .
    container_name: apt-cacher-ng
    ports:
      - "3142:3142"
    volumes:
      - apt-cacher-ng:/var/cache/apt-cacher-ng
    restart: always

volumes:
  apt-cacher-ng: